spring:
  h2.console.enabled: true

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt.secret: demo

message: Hello from application-local.yml configuration

server:
  port: 8081
